import { AnimatableSimulationParameters } from './parameter-animator';

const INITIAL = {
  DENSITY_DISSIPATION: 2,
  VELOCITY_DISSIPATION: 1,
  PRESSURE: 0.8,
  CURL: 4,
  SPLAT_RADIUS: 0.15,
};

const FAST_SWIRLS = {
  DENSITY_DISSIPATION: 1.7,
  VELOCITY_DISSIPATION: 0.3,
  PRESSURE: 0.9544213,
  CURL: 7,
  SPLAT_RADIUS: 0.16,
};

const CENTERED_ROUND_FAST = {
  DENSITY_DISSIPATION: 0.5,
  VELOCITY_DISSIPATION: 4,
  PRESSURE: 0,
  CURL: 0,
  SPLAT_RADIUS: 0.216,
};

const SMALL_PUSHY_SWIRLS = {
  DENSITY_DISSIPATION: 1.4,
  VELOCITY_DISSIPATION: 0.2,
  PRESSURE: 0,
  CURL: 0,
  SPLAT_RADIUS: 0.4,
};
const ROUND_FULL = {
  DENSITY_DISSIPATION: 0.8,
  VELOCITY_DISSIPATION: 4,
  PRESSURE: 1,
  CURL: 0,
  SPLAT_RADIUS: 0.06,
};

const ROUND_THIN = {
  DENSITY_DISSIPATION: 0.8,
  VELOCITY_DISSIPATION: 4,
  PRESSURE: 0,
  CURL: 0,
  SPLAT_RADIUS: 0.06,
};

const VERY_CURLY_CENTER = {
  DENSITY_DISSIPATION: 4,
  VELOCITY_DISSIPATION: 0.52,
  PRESSURE: 0.2,
  CURL: 25,
  SPLAT_RADIUS: 0.216,
};

const SMEARY_FAST_NICE = {
  DENSITY_DISSIPATION: 2,
  VELOCITY_DISSIPATION: 4,
  PRESSURE: 0.0625,
  CURL: 1,
  SPLAT_RADIUS: 0.188,
};

const SMEARY_FULL = {
  DENSITY_DISSIPATION: 1.0103445913543878,
  VELOCITY_DISSIPATION: 4,
  PRESSURE: 0.6,
  CURL: 1,
  SPLAT_RADIUS: 0.173,
};

const SQUID_SWIRLS = {
  DENSITY_DISSIPATION: 1.9573885044872235,
  VELOCITY_DISSIPATION: 4,
  PRESSURE: 1,
  CURL: 20,
  SPLAT_RADIUS: 0.283,
};

const parameterSets: AnimatableSimulationParameters[] = [
  INITIAL,
  FAST_SWIRLS,
  CENTERED_ROUND_FAST,
  SMALL_PUSHY_SWIRLS,
  ROUND_FULL,
  ROUND_THIN,
  VERY_CURLY_CENTER,
  SMEARY_FAST_NICE,
  SMEARY_FULL,
  SQUID_SWIRLS,
];

export default parameterSets;
